name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Copy repository to droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "."
      
      - name: Build and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker build -t slime-server .
            docker stop slime-server || true
            docker rm slime-server || true
            docker run -d --name slime-server -p 8080:8080 slime-server